[build]
  publish = "public"
  command = "npx pnpm install --store=node_modules/.pnpm-store && npm run build"
[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # prevent Netlify npm install
[[redirects]]
  from = "/cv"
  to = "https://cv.hung.dev/"
  status = 301
  force = false

[[redirects]]
  from = "/trochuyenit"
  to = "https://trochuyenit.hung.dev/?utm_source=blog"
  status = 301
  force = false

[[redirects]]
  from = "/podcast"
  to = "https://trochuyenit.hung.dev/?utm_source=blog"
  status = 301
  force = false

[[redirects]]
  from = "/hello-hung-dev"
  to = "/posts/hello-hung-dev"

[[redirects]]
  from = "/clean-code-1"
  to = "/posts/clean-code-1"

[[redirects]]
  from = "/safe-password"
  to = "/posts/safe-password"

[[redirects]]
  from = "/bai-hoc-cho-tam-tri-khi-chay-cham"
  to = "/posts/bai-hoc-cho-tam-tri-khi-chay-cham"

[[redirects]]
  from ="/slack-api-lixi"
  to = "/posts/slack-api-lixi"

[[redirects]]
  from = "/referrer-policy"
  to = "/posts/referrer-policy"

[[redirects]]
  from = "/safe-internet"
  to = "/posts/safe-internet"

[[redirects]]
  from = "/choose-third-party-package"
  to = "/posts/choose-third-party-package"

[[redirects]]
  from = "/tich-xanh-github"
  to = "/posts/tich-xanh-github"

[[redirects]]
  from = "/learned-2021"
  to = "/posts/learned-2021"

[[redirects]]
  from = "/jest-vite"
  to = "/posts/jest-vite"

[[redirects]]
  from = "/posts/2021-12-30-authentic-v%E1%BB%9Bi-t%C3%ADch-xanh-tr%C3%AAn-github/tich-xanh-github"
  to = "/posts/tich-xanh-github"

[[redirects]]
  from = "/posts/safe-password/safe-password"
  to = "/posts/safe-password"

[[redirects]]
  from = "/posts/clean-code/clean-code-1"
  to = "/posts/clean-code-1"
